---

- name: gather required facts
  setup:
    gather_subset: [min]
  when: ansible_distribution_release is not defined

- name: install
  include_tasks: install.yml
  when: proxysql_exporter_setup == "full" or proxysql_exporter_setup == "install"

- name: configure
  import_tasks: configure.yml
  when: proxysql_exporter_setup == "full" or proxysql_exporter_setup == "configure"
